- balboa-agent/README.md
- build.sbt
- project/Balboa.scala
- project/BalboaAgent.scala
- project/plugins.sbt
Using SBT-Native-Packager, Balboa Agent assembly jars can now be packaged within .deb.  This allows us to publish artifiacts to S3 and utilize existing Socrata Deployment pipeline.
> Balboa Agent Debian Package

- project/BalboaAgent.scala
This introduces to string of a dependency.  Debian also does not manage java dependencies very well either.  Therefore we decided to move the java 7 dependency into the debian package recommendation list.
> Removed package dependency on openjdk-headless-jre.

- balboa-agent/src/main/resources/config/config.properties
- balboa-agent/src/main/resources/log4j.properties
* Balboa root project now aggregates Balboa Agent subproject
* Updated Balboa to latest Scala 2.10 patch
* Update sat-native-packager 1.0.2 -> 1.0.4
* Introduced drop wizard metrics for Balboa Agent
* Balboa Agent now utilizes SBT Native Packager JavaAppArchetype to manage distribution structure
* Balboa Agent now utilized Debian and Docker distribution.
* Metric Consumer tracks per instance metrics
* Balboa Agent uses Socrata/java base image and runs as socrata user.
> Balboa Agent Distribution and Metrics updates

- project/BalboaAgent.scala
- project/Dependencies.scala
After including the socrata-sbt-plugins we were having some trouble
with sbt assembly and dependencies.  This excludes the correct transient
dependencies.
> Balboa Assembly works once again

- balboa-client-jms/src/main/scala/com/socrata/balboa/impl/AsyncActiveMQQueue.scala
- balboa-client/src/main/scala/com/socrata/metrics/MetricQueue.scala
- balboa-service-kafka/src/main/scala/com/socrata/balboa/service/kafka/KafkaConsumerCLIBase.scala
- project/BalboaClient.scala
- project/BuildSettings.scala
* Updated syntax to Scala 2.11 standards
* Update build scripts.
> EN-2457: Publish balboa-client with Scala 2.11

- balboa-client-jms/src/main/java/com/blist/metrics/impl/queue/MetricJmsQueueNotSingleton.java
- balboa-client/src/main/java/com/blist/metrics/impl/queue/MetricsBuffer.java
* The buffercapacity in MetricJmsQueueNotSingleton was not being
utilized correctly.  This change fixes that.
NOTE: MetricJmsQueueNotSingleton should be refactored into
MetricJmsQueue.  This changes the interface and I deemed that it should
be released with this patch.
> Fixed Incorrect Buffer Capacity Def.

- project/BalboaClient.scala
- project/BalboaCommon.scala
- project/BalboaCore.scala
- project/BuildSettings.scala
Cross scala versions are now set at sub projects that require being
published to repo.socrata.com.
> Balboa HTTP build fix

- .travis.yml
Remove the .travis.yml that triggers CI builds in travis. travis-ci is
not our supported mechanism for executing CI builds.
> Remove the travis-ci build triggers.

- balboa-agent/src/main/resources/log4j.properties
When there are connection related problems, the ActiveMQ client
libraries handle the connection/reconnection, timeout and failover logic
invisibly. This change adds logging configuration to increase the level
of ActiveMQ logging specifically around connections and failovers. When
experimenting on my local machine, the amount of logging introduced by
this change is something on the order of 1-2 lines every few seconds,
when connection problems are happening.
> Increase ActiveMQ client library logging.

- balboa-core/src/main/scala/com/socrata/balboa/metrics/data/impl/Cassandra11QueryImpl.scala
balboa-jms is currently logging ~10 gigs of logs a day, and ~80%
of them are from this one log line, which doesn't seem overly useful
or necessary to log at non-debug levels.
> Bump down "Using entity/row key" log message to debug level from info.

- README.md
- build.sbt
- project/Balboa.scala
- project/BalboaClient.scala
- project/BalboaHttp.scala
balboa-client-* must be cross compiled for Scala 2.10 and 2.11 because
there are some projects of each version consuming them.
balboa-http can not be cross compiled for Scala 2.11 because the
socrata-http dependency is only in Scala 2.10.
The way our build system works it invokes all sbt tasks from the root
project:
sbt +balboa-client-dispatcher/compile
When `sbt` is invoked this way, it uses the crossScalaVersions setting
from the root project, not from the project being compiled.
In the end we fixed this by munging the build job on Jenkins to pass an
additional parameter to sbt, thusly:
sbt 'set crossScalaVersions = List("2.10.6", "2.11.7")' \
+balboa-client-dispatcher/compile
> Address cross compiling problems

- balboa-client-kafka/src/test/scala/com/socrata/balboa/impl/KafkaComponentTests.scala
- balboa-client-kafka/src/test/scala/com/socrata/balboa/impl/MetricLoggerToKafkaTests.scala
- balboa-client-kafka/src/test/scala/com/socrata/integration/kafka/util/BalboaClientTestHarnessSpec.scala
- balboa-client-kafka/src/test/scala/com/socrata/metrics/producer/BalboaKafkaProducerScenario1Tests.scala
- balboa-service-kafka/src/test/scala/com/socrata/balboa/service/kafka/consumer/BalboaConsumerGroupIntegrationTest.scala
- balboa-service-kafka/src/test/scala/com/socrata/balboa/service/kafka/consumer/BalboaConsumerTests.scala
- balboa-service-kafka/src/test/scala/com/socrata/balboa/service/kafka/consumer/KafkaConsumerComponentTests.scala
- balboa-service-kafka/src/test/scala/com/socrata/balboa/service/kafka/consumer/PersistentConsumerComponentTests.scala
- project/BalboaClient.scala
- project/BalboaService.scala
These tests are unstable and inconsistent on Jenkins, which is a real
barrier to pull requests. More to the point, we no longer support Kafka.
There is future work to delete this code:
https://socrata.atlassian.net/browse/EN-6069
For the moment, just disabling it.
> Disable kafka related tests.

- balboa-core/src/main/scala/com/socrata/balboa/metrics/data/impl/Cassandra11Util.scala
- balboa-http/docker/balboa.properties.j2
- balboa-service-jms/docker/balboa.properties.j2
- balboa-service-kafka/docker/balboa-kafka.properties.j2
If Cassandra datacenter is specified in configuration properties, apply
it as a DC local configuration.  Otherwise, behave as it has previously.
> EN-7053 - Add support for DC in C* configuration

- balboa-http/src/it/scala/com/socrata/balboa/server/MetricsIntegrationTest.scala
Note: protobuf response code tests purposefully left out of `/metrics/*/series` queries because the series endpoint does not support protobuf.
> Add badcall integration tests and protobuf response code tests to balboa-http

- balboa-core/src/main/scala/com/socrata/balboa/metrics/data/impl/Cassandra11Util.scala
- balboa-http/src/main/resources/config/config.properties
Cassandra does not handle mixed case names well, and it would be better
if people never used mixed case names.
If the keyspace name is mixed case, quote it before passing it to the
Datastax driver.
> Quote mixed case keyspace names.

- balboa-core/src/main/java/com/socrata/balboa/metrics/data/DataStoreFactory.java
- balboa-core/src/main/scala/com/socrata/balboa/metrics/data/impl/CassandraDataStore.scala
- balboa-core/src/main/scala/com/socrata/balboa/metrics/data/impl/CassandraQuery.scala
- balboa-core/src/main/scala/com/socrata/balboa/metrics/data/impl/CassandraQueryImpl.scala
- balboa-core/src/main/scala/com/socrata/balboa/metrics/data/impl/CassandraUtil.scala
- balboa-core/src/test/scala/com/socrata/balboa/metrics/data/impl/CassandraDataStoreTest.scala
- balboa-core/src/test/scala/com/socrata/balboa/metrics/data/impl/CassandraQueryImplTest.scala
- balboa-core/src/test/scala/com/socrata/balboa/metrics/data/impl/MockCassandraQueryImpl.scala
It appears that Long Long Ago, someone named some Cassandra related classes with `11`, which I believe indicated Cassandra 1.1. That is no longer true, and will get less true as time goes on.
> Renamed Cassandra related classes.

- balboa-core/src/main/scala/com/socrata/balboa/metrics/data/impl/CassandraQueryImpl.scala
- balboa-http/src/it/scala/com/socrata/balboa/server/MetricsIntegrationTest.scala
This fixes a bug when attempting to persist a combined collection of aggregate and non-aggregate metrics. Aggregate metrics must be persisted through a separate query from non-aggregates, as they require a counter batch, while non-aggregates require a non-counter batch. See discussion [here](http://www.datastax.com/dev/blog/atomic-batches-in-cassandra-1-2) and [here](https://datastax-oss.atlassian.net/browse/NODEJS-158).
> Fixed persisting of aggregate metrics

- balboa-http/src/main/scala/com/socrata/balboa/server/MetricsServlet.scala
Fixed a bug where the timers' `toString` was being returned as the response body in some balboa-http endpoints.
> Evaluate timers for results in balboa-http

- balboa-agent/src/it/scala/com/socrata/balboa/agent/RemoveQueue.scala
- balboa-agent/src/main/scala/com/socrata/balboa/agent/BalboaAgent.scala
- balboa-agent/src/main/scala/com/socrata/balboa/agent/HttpMetricQueue.scala
- balboa-agent/src/main/scala/com/socrata/balboa/agent/LoggingTransportListener.scala
- balboa-agent/src/main/scala/com/socrata/balboa/agent/MetricFileProvider.scala
- balboa-agent/src/main/scala/com/socrata/balboa/agent/metrics/BalboaAgentMetrics.scala
- balboa-agent/src/test/scala/com/socrata/balboa/agent/HttpMetricQueueSpec.scala
- balboa-agent/src/test/scala/com/socrata/balboa/agent/MetricConsumerSpec.scala
- balboa-client-jms/src/main/scala/com/socrata/balboa/impl/ActiveMessageQueue.scala
- balboa-core/src/main/scala/com/socrata/balboa/metrics/data/impl/BadIdeasDataStore.scala
- balboa-core/src/main/scala/com/socrata/balboa/metrics/data/impl/CassandraDataStore.scala
- balboa-core/src/main/scala/com/socrata/balboa/metrics/data/impl/CassandraQueryImpl.scala
- balboa-core/src/main/scala/com/socrata/balboa/metrics/data/impl/CassandraUtil.scala
- balboa-http/src/main/scala/ScalatraBootstrap.scala
- balboa-http/src/main/scala/com/socrata/balboa/server/ClientCounter.scala
- balboa-http/src/main/scala/com/socrata/balboa/server/Main.scala
- balboa-http/src/main/scala/com/socrata/balboa/server/MainServlet.scala
- balboa-http/src/main/scala/com/socrata/balboa/server/MetricsServlet.scala
- balboa-http/src/main/scala/com/socrata/balboa/server/UnexpectedErrorFilter.scala
- balboa-service-kafka/src/main/scala/com/socrata/balboa/service/kafka/BalboaKafkaConsumerCLI.scala
- balboa-service-kafka/src/main/scala/com/socrata/balboa/service/kafka/consumer/BalboaConsumerGroup.scala
- balboa-service-kafka/src/main/scala/com/socrata/balboa/service/kafka/consumer/PersistentKafkaConsumerComponent.scala
- project/BalboaAgent.scala
- project/BalboaCommon.scala
- project/BalboaCore.scala
- project/Dependencies.scala
This is a blocker for getting Gatling load testing integrated into balboa, as Gatling depends on scala-logging which is incorrectly resolved when scala-logging-slf4j is included.
> Switch from scala-logging-slf4j to updated version scala-logging

- jenkins/integration-tests
The integration tests for balboa-agent include a clean up step that
attempts to remove the ActiveMQ queue used by the tests. When there is
no ActiveMQ broker available, that steps hangs infinitely because the
ActiveMQ client libraries by default do infinite retry on a connection.
https://socrata.atlassian.net/browse/EN-7819 is to address this issue and fully enable the integration tests.
> Disable balboa-agent integration tests on Jenkins.

- balboa-http/src/main/scala/ScalatraBootstrap.scala
Internally collected application metrics (counters and timers relating
to the functioning of balboa-http itself) are published into graphite
using JmxReporter, which sends the metrics to the collectd instance in
the Docker container (which handlers transferring them on to the final
destination.)
> Enable metrics reporting in balboa-http.

- balboa-http/src/it/bash/integration-tests
- balboa-http/src/it/bash/rc.config
- balboa-http/src/it/bash/staging.config
- etc/balboa-cassandra.cql
- jenkins/integration-tests
Add support for starting a Docker container with a Cassandra instance,
importing the necessary schema and connecting balboa-http to the
instance for the integration tests.
> Update balboa-http integration tests

- balboa-http/docker/Dockerfile
- balboa-http/docker/run
- balboa-service-jms/docker/Dockerfile
- balboa-service-jms/docker/ship.d/run
The necessary JMX settings to correctly integrate with collectd metrics
collections are inherited from the socrata/runit-java8 image in the form
of JAVA_TOOL_OPTIONS. This change removes the balboa image specific
overrides.
> Stop setting the JMX port.

- balboa-http/src/main/scala/com/socrata/balboa/server/MainServlet.scala
- balboa-http/src/main/scala/com/socrata/balboa/server/MetricsServlet.scala
- balboa-http/src/main/scala/com/socrata/balboa/server/SocrataMetricsSupport.scala
The names of timing metrics used for reporting the behavior of the
balboa-http service were preserved in their original format for
backwards compatibility. However, after spending much time
troubleshooting and trying to make metrics publishing actually work, I
can only conclude it never worked, and there is nothing to be backwards
compatible with, so I'm changing the metrics names to something more
useful.
> Change service metric names.

- balboa-http/src/main/scala/ScalatraBootstrap.scala
- balboa-http/src/main/scala/com/socrata/balboa/server/LogLevel.scala
- balboa-http/src/main/scala/com/socrata/balboa/server/Main.scala
This is a stopgap solution to resolve EN-9166 that should
be replaced by the upcoming work to change the way balboa
is configured (possibly using typesafe config).
> Hack commandline log-level setting into balboa-http

- balboa-service-jms/src/main/resources/log4j.properties
Logs now look something like...
```
[INFO] 11-07-2016 12:54:20 c.s.b.j.BalboaJms main - Receivers starting, awaiting messages.
[INFO] 11-07-2016 12:54:20 c.s.b.m.d.i.CassandraUtil$ initializeContext - Connecting to Cassandra servers 'localhost:9042'
[INFO] 11-07-2016 12:54:20 c.s.b.m.d.i.CassandraUtil$ initializeContext - Defaulting Cassandra client configuration to use all available datacenters
[INFO] 11-07-2016 12:54:20 c.s.b.m.d.i.CassandraUtil$ initializeContext - Using maximum size of '10' for Cassandra connection pool.
[INFO] 11-07-2016 12:54:20 c.s.b.m.d.i.CassandraUtil$ initializeContext - Setting Cassandra socket timeout to '120000'
[INFO] 11-07-2016 12:54:20 c.s.b.m.d.i.CassandraUtil$ initializeContext - Using keyspace 'Metrics2012'
[INFO] 11-07-2016 12:54:20 …
```
> EN-10146: Add date and other stuff to balboa-service-jms logging

- balboa-agent/src/it/bash/integration-tests
- balboa-agent/src/it/resources/application.conf
- balboa-agent/src/it/scala/com/socrata/balboa/agent/IntegrationTestConfig.scala
- balboa-agent/src/it/scala/com/socrata/balboa/agent/WriteMetricIntegrationTest.scala
- balboa-agent/src/main/scala/com/socrata/balboa/agent/MetricConsumer.scala
- balboa-agent/src/test/scala/com/socrata/balboa/agent/MetricConsumerSpec.scala
* Load metric files into memory for processing instead of using memory-mapped
files.  Memory-mapped file handlers will not be fully closed until a
garbage collection occurs.  Instead, we will just load the metric files
into memory and process them there.
* Add integration test for open file descriptors
* Also refactor integration tests a bit
> EN-14710: Fix dangling file handlers

- balboa-service-jms/src/main/resources/log4.properties
This is to help with Sumo being able to ingest these log lines without
putting each line of the stacktrace in its own log line.
> EN-36732: Avoid logging stacktrace line-by-line

- balboa-http/src/it/bash/integration-tests
Prior to this change, the balboa-http integration test script would fail
due to it being unable to determine the docker0 network interface IP
address. This appears to be due to changes in the output of ifconfig in
Ubuntu 18.04.
This change determines the IP address by using docker inspect with an
output formatter instead of parsing the output of ifconfig.
> NO-JIRA: Fix broken integration test script

- balboa-service-jms/docker/ship.d/run
Prior to this change, it is speculated that a long-running
balboa-service-jms instance could get into a state that would cause an
accumulation of messages in the Metrics2012 and Metrics2012.DLQ ActiveMQ
queues, eventually paging the on-call engineer and requiring manual
intervention to restart and scale the balboa-service-jms instances.
This change modifies the run script for balboa-service-jms' docker
container to automatically kill the main process, and thus the whole
container, approximately every 24 hours.  At this point Marathon will
replace the container with a fresh one, preventing any one container
from living longer than approximately 24 hours.
> EN-36770: Periodically kill balboa-service-jms

- balboa-http/docker/Dockerfile
To test this, I followed the instructions in balboa-http/docker/readme.md.  The docker container ran just fine without error.
> EN-35141: Upgraded balboa-http to ubuntu 18.04
